name: homework
version: '1.0.0'
config-version: 2
profile: homework
require-dbt-version: [">=1.11.0", "<1.12.0"]
model-paths: [models]
test-paths: [tests]
macro-paths: [macros]
models:
  homework:
    +persist_docs:
      relation: true
      columns: true
    +copy_grants: true
    staging:
      +schema: STAGING
      +materialized: view
    marts:
      +schema: MARTS
      +materialized: table
