USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS HOMEWORK_ENGINEER;
GRANT ROLE HOMEWORK_ENGINEER TO ROLE SYSADMIN;
SET setup_user = CURRENT_USER();
GRANT ROLE HOMEWORK_ENGINEER TO USER IDENTIFIER($setup_user);

CREATE WAREHOUSE IF NOT EXISTS HOMEWORK_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;
GRANT USAGE ON WAREHOUSE HOMEWORK_WH TO ROLE HOMEWORK_ENGINEER;

CREATE DATABASE IF NOT EXISTS HOMEWORK;
CREATE SCHEMA IF NOT EXISTS HOMEWORK.RAW;
CREATE SCHEMA IF NOT EXISTS HOMEWORK.STAGING;
CREATE SCHEMA IF NOT EXISTS HOMEWORK.MARTS;

GRANT USAGE ON DATABASE HOMEWORK TO ROLE HOMEWORK_ENGINEER;
GRANT USAGE ON SCHEMA HOMEWORK.RAW TO ROLE HOMEWORK_ENGINEER;
GRANT USAGE ON SCHEMA HOMEWORK.STAGING TO ROLE HOMEWORK_ENGINEER;
GRANT USAGE ON SCHEMA HOMEWORK.MARTS TO ROLE HOMEWORK_ENGINEER;
GRANT CREATE TABLE ON SCHEMA HOMEWORK.RAW TO ROLE HOMEWORK_ENGINEER;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA HOMEWORK.STAGING TO ROLE HOMEWORK_ENGINEER;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA HOMEWORK.MARTS TO ROLE HOMEWORK_ENGINEER;
