USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS HOMEWORK_REVIEWER_ROLE;
CREATE WAREHOUSE IF NOT EXISTS REVIEWER_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

GRANT USAGE ON WAREHOUSE REVIEWER_WH TO ROLE HOMEWORK_REVIEWER_ROLE;
GRANT USAGE ON DATABASE HOMEWORK TO ROLE HOMEWORK_REVIEWER_ROLE;
GRANT USAGE ON SCHEMA HOMEWORK.MARTS TO ROLE HOMEWORK_REVIEWER_ROLE;
GRANT SELECT ON TABLE HOMEWORK.MARTS.DIM_CUSTOMER TO ROLE HOMEWORK_REVIEWER_ROLE;
GRANT SELECT ON TABLE HOMEWORK.MARTS.DIM_PRODUCT TO ROLE HOMEWORK_REVIEWER_ROLE;
GRANT SELECT ON TABLE HOMEWORK.MARTS.FCT_ORDERS TO ROLE HOMEWORK_REVIEWER_ROLE;
GRANT SELECT ON TABLE HOMEWORK.MARTS.FCT_ORDER_ITEMS TO ROLE HOMEWORK_REVIEWER_ROLE;
GRANT SELECT ON VIEW HOMEWORK.MARTS.AGG_WEEKLY_PRODUCT TO ROLE HOMEWORK_REVIEWER_ROLE;

-- Create the reviewer user privately using SETUP.md, then assign this role.
