USE ROLE HOMEWORK_ENGINEER;
USE WAREHOUSE HOMEWORK_WH;

SELECT 'raw' AS object_name, COUNT(*) AS row_count FROM HOMEWORK.RAW.HOMEWORK_OBT
UNION ALL SELECT 'customers', COUNT(*) FROM HOMEWORK.MARTS.DIM_CUSTOMER
UNION ALL SELECT 'products', COUNT(*) FROM HOMEWORK.MARTS.DIM_PRODUCT
UNION ALL SELECT 'orders', COUNT(*) FROM HOMEWORK.MARTS.FCT_ORDERS
UNION ALL SELECT 'items', COUNT(*) FROM HOMEWORK.MARTS.FCT_ORDER_ITEMS;

SELECT COUNT(DISTINCT week_start) AS weeks,
    COUNT(*) AS week_product_rows
FROM HOMEWORK.MARTS.AGG_WEEKLY_PRODUCT;

SELECT product_id, COUNT(*) AS weeks_as_top_seller
FROM HOMEWORK.MARTS.AGG_WEEKLY_PRODUCT
WHERE is_top_seller = 1
GROUP BY 1 ORDER BY 1;

SELECT * FROM HOMEWORK.MARTS.AGG_WEEKLY_PRODUCT
WHERE week_start = '2024-05-27' ORDER BY revenue DESC;

SELECT COUNT_IF(customer_phone IS NULL) AS missing_phones,
    COUNT_IF(customer_email IS NULL) AS missing_emails
FROM HOMEWORK.MARTS.DIM_CUSTOMER;
